# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdh', '0018_auto_20170420_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='profile_picture',
            field=models.ImageField(upload_to='profile-picture/'),
        ),
    ]
