# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdh', '0021_auto_20170421_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalworkdata',
            name='treatment_batch_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vetmedicinedistributiondata',
            name='balance_in_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vetmedicinedistributiondata',
            name='distributed_batch_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vetmedicinedistributiondata',
            name='distributed_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vetmedicinedistributiondata',
            name='opening_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vetmedicinedistributiondata',
            name='procured_batch_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vetmedicinedistributiondata',
            name='procured_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vetmedicineproductiondata',
            name='balance_in_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vetmedicineproductiondata',
            name='distributed_batch_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vetmedicineproductiondata',
            name='distributed_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vetmedicineproductiondata',
            name='opening_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vetmedicineproductiondata',
            name='produced_batch_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vetmedicineproductiondata',
            name='produced_quantity',
            field=models.IntegerField(),
        ),
    ]
