# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdh', '0022_auto_20170423_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vpp',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('kvb_reg_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('academic_inst', models.CharField(max_length=100)),
                ('program_studied', models.CharField(choices=[('CERT', 'Certificate in AH'), ('DIP', 'Diploma in AH'), ('BSC', 'Bachelor of Science in AH'), ('BVM', 'Bachelor of Science in Vetenary Medicine')], max_length=100)),
                ('index_no', models.IntegerField(unique=True)),
                ('year_of_graduation', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('academic_cert_reg_no', models.IntegerField(unique=True)),
                ('any_other_certs', models.CharField(max_length=500)),
                ('license_no', models.IntegerField(unique=True)),
                ('license_exp_date', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('current_station_of_work', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='vet',
            name='is_vpp',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='supervising_vet',
        ),
        migrations.DeleteModel(
            name='SupervisingVet',
        ),
        migrations.AddField(
            model_name='vpp',
            name='supervising_vet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='vdh.Vet'),
        ),
    ]
