# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdh', '0023_auto_20170517_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetMedicineDistributerProfile',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('kvb_reg_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('academic_inst', models.CharField(max_length=100)),
                ('program_studied', models.CharField(choices=[('CERT', 'Certificate in AH'), ('DIP', 'Diploma in AH'), ('BSC', 'Bachelor of Science in AH'), ('BVM', 'Bachelor of Science in Vetenary Medicine')], max_length=100)),
                ('index_no', models.IntegerField(unique=True)),
                ('year_of_graduation', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('academic_cert_reg_no', models.IntegerField(unique=True)),
                ('any_other_certs', models.CharField(max_length=500)),
                ('license_no', models.IntegerField(unique=True)),
                ('license_exp_date', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('current_station_of_work', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VetMedicineProducerProfile',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('kvb_reg_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('academic_inst', models.CharField(max_length=100)),
                ('program_studied', models.CharField(choices=[('CERT', 'Certificate in AH'), ('DIP', 'Diploma in AH'), ('BSC', 'Bachelor of Science in AH'), ('BVM', 'Bachelor of Science in Vetenary Medicine')], max_length=100)),
                ('index_no', models.IntegerField(unique=True)),
                ('year_of_graduation', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('academic_cert_reg_no', models.IntegerField(unique=True)),
                ('any_other_certs', models.CharField(max_length=500)),
                ('license_no', models.IntegerField(unique=True)),
                ('license_exp_date', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('current_station_of_work', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('kvb_reg_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('academic_inst', models.CharField(max_length=100)),
                ('program_studied', models.CharField(choices=[('CERT', 'Certificate in AH'), ('DIP', 'Diploma in AH'), ('BSC', 'Bachelor of Science in AH'), ('BVM', 'Bachelor of Science in Vetenary Medicine')], max_length=100)),
                ('index_no', models.IntegerField(unique=True)),
                ('year_of_graduation', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('academic_cert_reg_no', models.IntegerField(unique=True)),
                ('any_other_certs', models.CharField(max_length=500)),
                ('license_no', models.IntegerField(unique=True)),
                ('license_exp_date', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('current_station_of_work', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VppProfile',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('kvb_reg_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('academic_inst', models.CharField(max_length=100)),
                ('program_studied', models.CharField(choices=[('CERT', 'Certificate in AH'), ('DIP', 'Diploma in AH'), ('BSC', 'Bachelor of Science in AH'), ('BVM', 'Bachelor of Science in Vetenary Medicine')], max_length=100)),
                ('index_no', models.IntegerField(unique=True)),
                ('year_of_graduation', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('academic_cert_reg_no', models.IntegerField(unique=True)),
                ('any_other_certs', models.CharField(max_length=500)),
                ('license_no', models.IntegerField(unique=True)),
                ('license_exp_date', models.DateField(help_text='Please use the following format: <em>MM-DD-YYYY</em>.')),
                ('current_station_of_work', models.CharField(max_length=100)),
                ('supervising_vet', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='vdh.VetProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vpp',
            name='supervising_vet',
        ),
        migrations.AddField(
            model_name='clinicalworkdata',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vetmedicinedistributiondata',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vetmedicineproductiondata',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vetmedicinedistributiondata',
            name='distributed_to',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vdh.VetProfile'),
        ),
        migrations.AlterField(
            model_name='vetmedicinedistributiondata',
            name='procured_from',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vdh.VetMedicineProducerProfile'),
        ),
        migrations.AlterField(
            model_name='vetmedicineproductiondata',
            name='distributed_to',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vdh.VetMedicineDistributerProfile'),
        ),
        migrations.DeleteModel(
            name='Vet',
        ),
        migrations.DeleteModel(
            name='VetMedicineDistributer',
        ),
        migrations.DeleteModel(
            name='VetMedicineProducer',
        ),
        migrations.DeleteModel(
            name='Vpp',
        ),
    ]
