# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdh', '0024_auto_20170604_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetmedicinedistributerprofile',
            name='any_other_certs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vetmedicineproducerprofile',
            name='any_other_certs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vetprofile',
            name='any_other_certs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vetprofile',
            name='user',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='vppprofile',
            name='any_other_certs',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
