# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdh', '0004_remove_practitioner_supervising_vet'),
    ]

    operations = [
    ]
