# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdh', '0008_remove_practitioner_supervising_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitioner',
            name='supervising_vet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='vdh.Vet'),
        ),
    ]
