# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdh', '0013_delete_vet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('profile_picture', models.ImageField(upload_to='profile-pictures/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('kvb_reg_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('academic_inst', models.CharField(max_length=100)),
                ('program_studied', models.CharField(choices=[('CERT', 'Certificate in AH'), ('DIP', 'Diploma in AH'), ('BSC', 'Bachelor of Science in AH'), ('BVM', 'Bachelor of Science in Vetenary Medicine')], max_length=100)),
                ('index_no', models.IntegerField(unique=True)),
                ('year_of_graduation', models.DateField()),
                ('academic_cert_reg_no', models.IntegerField(unique=True)),
                ('any_other_certs', models.CharField(max_length=500)),
                ('license_no', models.IntegerField(unique=True)),
                ('license_exp_date', models.DateField()),
                ('current_station_of_work', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='practitioner',
            name='supervising_vet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='vdh.Vet'),
        ),
    ]
